[package]
name = "sts2-game-mod-interop"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false
license.workspace = true

[lib]
name = "ai_ascension_sts2_game_mod_native"
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
